### ISSUE TITLE
Migrate dashboard developments to 2.28

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dashboard-classic-app#1]
This [PR](https://github.com/dhis2/dhis2-core/pull/429) got into 2.25 but was never backported to master. So we don't have this feature in 2.28. We would like to create a PRs migrating this feature

**Comment by tokland** [comment]
Only 2.28/master.

**Comment by tokland** [comment]
Pushed changes to dashboard-app, d2-analysis, dhis2-pivot, dhis2-visualized. In all of them, branch feature/2.28-interpretations-improvements against 2.28 (<- dhis2 upstream/master). There is a temporal code (which may not be temporal, if we don't find a better way, on d2-analytis, comments on the PR). Otherwise, it can be reviewed.

https://github.com/EyeSeeTea/dhis2-visualizer/pull/3
https://github.com/EyeSeeTea/dhis2-pivot/pull/7
https://github.com/EyeSeeTea/d2-analysis/pull/16
https://github.com/EyeSeeTea/dashboard-app/pull/2

**Comment by adrianq** [comment]
PRs created!
https://github.com/dhis2/dashboard-app/pull/11
https://github.com/dhis2/pivot-tables-app/pull/84
https://github.com/dhis2/charts-app/pull/34
https://github.com/dhis2/d2-analysis/pull/47
